name: Deploy on QA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_on_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Create customer Env file
        working-directory: ./customer
        run: |
          touch .env.dev
          echo APP_JWT_KEY=${{ secrets.QA_APP_SECRET }} >> .env.dev
          echo MONGODB_URL=${{ secrets.QA_DB_URL }} >> .env.dev
          echo MESSAGE_BROKER_URL=${{ secrets.QA_MSG_QUEUE_URL }} >> .env.dev
          echo EXCHANGE_NAME=DATA_EXCHANGE >> .env.dev
          echo PORT=8001 >> .env.dev
          cat .env.dev

      - name: Create codecamps Env file
        working-directory: ./codecamps
        run: |
          touch .env.dev
          echo APP_JWT_KEY=${{ secrets.QA_APP_SECRET }} >> .env.dev
          echo MONGODB_URL=${{ secrets.QA_DB_URL }} >> .env.dev
          echo MESSAGE_BROKER_URL=${{ secrets.QA_MSG_QUEUE_URL }} >> .env.dev
          echo EXCHANGE_NAME=DATA_EXCHANGE >> .env.dev
          echo PORT=8003 >> .env.dev
          cat .env.dev

      - name: Create courses Env file
        working-directory: ./courses
        run: |
          touch .env.dev
          echo APP_JWT_KEY=${{ secrets.QA_APP_SECRET }} >> .env.dev
          echo MONGODB_URL=${{ secrets.QA_DB_URL }} >> .env.dev
          echo MESSAGE_BROKER_URL=${{ secrets.QA_MSG_QUEUE_URL }} >> .env.dev
          echo EXCHANGE_NAME=DATA_EXCHANGE >> .env.dev
          echo PORT=8002 >> .env.dev
          cat .env.dev

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy on Elastic Beanstalk QA Env
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: codemarch-backend-application
          environment_name: Codemarch-backend-application-env
          version_label: "ver-${{ github.run_id }}-${{ github.sha }}"
          region: ap-south-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true
